# Etapa 1: Imagem base
FROM php:8.0-fpm

# Etapa 2: Instalação de dependências
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
    && docker-php-ext-install pdo pdo_mysql

# Etapa 3: Definir o diretório de trabalho
WORKDIR /var/www

# Etapa 4: Copiar arquivos da aplicação
COPY . .

# Etapa 5: Instalar Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Etapa 6: Instalar dependências do Laravel
RUN composer install

# Etapa 7: Expor a porta 9000
EXPOSE 9000

# Comando para iniciar o PHP-FPM
CMD ["php-fpm"]
